<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ماندن یا نماندن؛ مسئله اینست
</font>
</h1>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توضیحات ابتدایی
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در درسنامه‌های گذشته با حذف مقادیر از داده و مدیریت مقادیر گمشده آشنا شدیم. حال در این تمرین قصد داریم با تمرین و کد زدن مهارت خود را به چالش بکشیم!
    <br>
    فایل migration_rate.csv آمار مهاجرت به و مهاجرت از کشور‌های مختلف را از سال ۱۹۹۰ تا ۲۰۲۰ نشان می‌دهد. هدف این تمرین، تحلیل نرخ مهاجرت تعدادی از کشورهای موجود در این فایل است.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
| نام ستون| توضیح ستون|
|:------------------:|:------------------:|
| Country | نام کشور |
| 1990   | در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۰ آمده‌است.|
| 1995   |در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۵ آمده‌است.|
| 2000   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۰ آمده‌است.|
| 2005   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۵ آمده‌است.|
| 2010   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۰ آمده‌است.|
| 2015   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۵ آمده‌است.|
| 2020   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۲۰ آمده‌است.|

</font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    فرمول محاسبه نرخ مهاجرت
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    شاید برایتان سوال شده باشد، نرخ مهاجرت هر کشور چگونه محاسبه شده است!
    <br>
    نرخ مهاجرت حاصل نسبت تفاوت مهاجران به کشور و مهاجران از کشور، به جمعیت کشور در آن سال به ازای هر ۱۰۰۰ نفر است. به فرمول زیر توجه کنید.
    </font>
</p>


<p dir=rtl style="text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=5>
    $\frac{(migration in - migration out) * 1000 }{population}$
</font>
</p>

<p dir=rtl style="direction:trl; text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این فرمول در حل مسئله هیچ تاثیری ندارد، بلکه فقط برای درک بهتر آورده شده‌است.
</font>
</p>

In [28]:
import numpy as np
import pandas as pd 

In [29]:
# read csv file in df
df = pd.read_csv('./migration_rate.csv')
df

Country  1990  1995  2000  2005  2010  2015  2020
0         United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                 India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2    Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3               Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4               Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
..                  ...   ...   ...   ...   ...   ...   ...   ...
186                Mali -12.1  -3.8  -2.8  -1.1  -1.4  -3.7  -2.1
187          Costa Rica   1.2   4.2   4.8   2.0   1.4   0.8   0.8
188              Norway   1.8   2.2   2.7   3.0   6.9   8.8   5.3
189          Tajikistan  -1.3   NaN  -7.9  -4.5  -4.1  -3.4  -2.2
190              Angola   3.5   2.2   2.6   2.9   3.3   1.3   0.2

[191 rows x 8 columns]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
این تمرین در دو بخش آماده شده‌است. بخش اول به منظور پیش‌پردازش و بخش دوم برای پاسخدهی به تعدادی سوال تحلیلی از داده طراحی شده‌است.    
</font>
</p>



<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول : پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش از تحلیل باید مقادیر گم‌شده در داده را مدیریت کنید و برخی از اطلاعات را نیز از بین ببرید.
<br>
در گام پیش‌پردازش به ترتیب مراحل زیر را انجام دهید.
<ul>
    <li>
کشور‌هایی را که نرخ‌ مهاجرت در هر ۷ سال آن‌ها گم‌شده است از دیتاست برای همیشه حذف کنید.
    </li>
    <li>
مقادیر گمشده کشور‌هایی که اطلاعات برخی از سال‌ها را از دست داده‌اند را با میانگین آن کشور پر کنید. به‌عنوان مثال اگر نرخ مهاجرت کشوری از سال ۱۹۹۵ تا ۲۰۲۰ به ترتیب 5.2-، 3.4-، 0.7-، 0.9، 1.3 و 2.5 باشد، نرخ مهاجرت سال ۱۹۹۰ که گمشده بود را باید با عدد 0.76- پر کنید.
    </li>
</ul>
    </font>
</div>



<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام اول پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
        سطرهایی که نرخ هر ۷ سال در آن‌ها گمشده اند را حذف کنید.
</font>
</div>



In [30]:
# TODO: drop some rows
df = df.dropna(thresh=2)
df.shape

(185, 8)

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام دوم پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    مقادیر گمشده هر سطر را با میانگین آن سطر پر کنید.
</font>
</div>


In [31]:
# TODO: fill null values of rows
m = df.mean(axis=1)
for i, col in enumerate(df):
    df.iloc[:, i] = df.iloc[:, i].fillna(m)
df


/tmp/ipykernel_4083/1987529480.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  m = df.mean(axis=1)
/home/amin/Desktop/qenv/lib/python3.8/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Country  1990      1995  2000      2005  2010  2015  2020
0         United States   2.7  3.500000   6.5  3.700000  3.60   3.2   2.9
1                 India   0.0 -0.266667  -0.1 -0.300000 -0.40  -0.4  -0.4
2    Russian Federation   1.2  3.400000   3.2  2.500000  3.20   2.5   1.3
3               Germany   4.3  6.600000   1.8  4.033333  0.10   4.8   6.6
4               Algeria  -0.8 -0.900000  -1.1 -1.300000 -0.85  -0.8  -0.2
..                  ...   ...       ...   ...       ...   ...   ...   ...
186                Mali -12.1 -3.800000  -2.8 -1.100000 -1.40  -3.7  -2.1
187          Costa Rica   1.2  4.200000   4.8  2.000000  1.40   0.8   0.8
188              Norway   1.8  2.200000   2.7  3.000000  6.90   8.8   5.3
189          Tajikistan  -1.3 -3.900000  -7.9 -4.500000 -4.10  -3.4  -2.2
190              Angola   3.5  2.200000   2.6  2.900000  3.30   1.3   0.2

[185 rows x 8 columns]

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        بعد از اتمام هر دو مرحله پیش‌پردازش، تعداد مقادیر گمشده همه ستون‌ها باید 0 باشد.
    </font>
</div>

In [32]:
df.isna().sum()

Country    0
1990       0
1995       0
2000       0
2005       0
2010       0
2015       0
2020       0
dtype: int64

<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=3>
        متغیر <code>df</code> مورد داوری قرار خواهد گرفت، بنابراین به‌غیر از دو گام پیش‌پردازشی، هیچ‌گونه تغییری روی آن اعمال نکنید!
    </font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم : تحلیل
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
پس از اینکه ۲ مرحله بالا را انجام دادید به سوالات زیر پاسخ دهید.
    <br>
    قصد داریم با پاسخ به سوالات زیر، شهود دقیقی نسبت به وضع مهاجرت در برخی کشور‌ها به‌دست آوریم.
</font>
</div>



<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال اول
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سال ۲۰۲۰، <b>اسم</b> سه کشوری که بیشترین نرخ پذیرش مهاجر را دارند پیدا کنید. جواب خود را درون لیست <code>top_countries</code> ذخیره کنید. عنصر اول، دوم و سوم این لیست به ترتیب کشورهایی هستند که در رتبه اول تا سوم جذب مهاجر قرار می‌گیرند.
</font>
</div>



In [33]:
top_countries = df.sort_values('2020', ascending=False)[:3].Country.to_list()
#top_countries.name = None
#top_countries.index.name = None
top_countries

['Bahrain', 'Maldives', 'Oman']

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال دوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    میانگین نرخ مهاجرت کشور ایران در این بازه ۳۰ ساله محاسبه کرده و جواب را در متغیر <code>iran_mean</code> بنویسید. جنس این متغیر باید <code>numpy.float64</code> باشد.
    <br>
    اسم کشور ایران در این مجموعه داده به صورت <code>Iran (Islamic Republic of)</code> آمده‌است.
</font>
</div>



In [34]:
iran = df['Country'].str.contains('Iran')
iran_mean = df.loc[39][['1990', '1995', '2000', '2005', '2010', '2015', '2020']].mean()
iran_mean

-0.22857142857142865

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال سوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    <b>اسم</b> کشوری که در این بازه ۳۰ ساله، بیشترین رشد را داشته است در متغیر <code>highest_growth</code> بنویسید. این متغیر از نوع <i>str</i> است. منظور از رشد، تفاضل نرخ سال ۲۰۲۰ از سال ۱۹۹۰ است.

</font>
</div>



In [35]:
df_copy = df.copy()
df_copy['diff'] = df_copy.apply(lambda x: x['2020'] - x['1990'], axis=1)
max = df_copy['diff'].max()
highest_growth = df_copy[df_copy['diff'] == max].Country.to_string().split(" ")[-1]
highest_growth

'Liberia'

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    سلول جواب‌ساز
</font>
</h3>


In [36]:
import zipfile
import joblib

df.to_csv('./df.csv', index=False)
joblib.dump(top_countries,"top_countries")
joblib.dump(iran_mean,"iran_mean")
joblib.dump(highest_growth, "highest_growth")


def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["df.csv", "top_countries", "iran_mean", "highest_growth", "to_stay_or_not_to_stay.ipynb"]
compress(file_names)

File Paths:
['df.csv', 'top_countries', 'iran_mean', 'highest_growth', 'to_stay_or_not_to_stay.ipynb']
